name: finance_mcp
description: A MCP server to fetch financial statements from SEC EDGAR.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.6.0
  logging: ^1.3.0
  mcp_dart: ^1.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
